name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Initialize Buildozer
      run: buildozer init

    - name: Configure Buildozer spec
      run: |
        sed -i 's/title = Your Application/title = My Flask App/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = pursuex/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.example/' buildozer.spec
        sed -i "s/# (list) Application requirements/requirements = python3,kivy,flask,gunicorn/" buildozer.spec
        sed -i 's/source.dir = .\/main.py/source.dir = ./' buildozer.spec
        sed -i 's/#android.p4a.branch = master/android.p4a.branch = master/' buildozer.spec

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk

